...
/* FLEDS: Incluyo el stack al total */
#define	TOT_STACK_SPACE		(TTY_STACK + DP8390_STACK + SCSI_STACK + \
	SYN_ALRM_STACK + IDLE_STACK + HARDWARE_STACK + PRINTER_STACK + \
	WINCH_STACK + FLOP_STACK + MEM_STACK + CLOCK_STACK + SYS_STACK + \
	CDROM_STACK + AUDIO_STACK + MIXER_STACK + FLEDS_STACK)
...
